version: '3.8'
services:
  app:
    image: elzat7/sweter:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sweter
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sweter
    volumes:
      - db_data:/var/lib/mysql
      - ./uploads:/app/uploads
  nginx:
    image: public.ecr.aws/nginx/nginx:1.27-bookworm
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  db_data:
